@ECHO OFF
IF EXIST ..\src\Makefile GOTO BEGIN
CALL configure.cmd
:BEGIN
CD ..\src
@MAKE@ %1
IF ERRORLEVEL 1 GOTO ERROR
CD ..\os2
ECHO Compilation finished.
GOTO END
:ERROR
CD ..\os2
ECHO Compilation aborted !
:END
